DROP TABLE IF EXISTS recents;
DROP TABLE IF EXISTS sourceids;

CREATE TABLE recents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  bookdate TEXT,
  imglink TEXT
);

CREATE TABLE sourceids (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sourceid TEXT
)